# Generated by Django 2.2.11 on 2020-04-05 06:37

from django.db import migrations, models
import hash.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('meta_keywords', models.CharField(blank=True, help_text='Separate keywords by comma.', max_length=255, verbose_name='Keywords')),
                ('meta_title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitle')),
                ('paragraph1', models.TextField(max_length=350, verbose_name='Description1')),
                ('paragraph2', models.TextField(max_length=350, verbose_name='Description2')),
                ('paragraph3', models.TextField(max_length=350, verbose_name='Description3')),
                ('image', models.ImageField(upload_to=hash.models.upload_to, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Algorithm',
                'verbose_name_plural': 'Algorithms',
            },
        ),
    ]
