# Generated by Django 2.2.11 on 2020-04-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('meta_keywords', models.CharField(blank=True, help_text='Separate keywords by comma.', max_length=255, verbose_name='Keywords')),
                ('meta_title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Algorithm',
                'verbose_name_plural': 'Algorithms',
            },
        ),
    ]
