# Generated by Django 2.2.11 on 2020-04-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='slug',
        ),
    ]
