# Generated by Django 2.2.11 on 2020-04-05 08:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='stepper_description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='stepper_header',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='subtitle',
            field=models.CharField(max_length=250, verbose_name='Subtitle'),
        ),
    ]
