# Generated by Django 2.2.11 on 2020-04-05 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0002_remove_algorithm_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(default='', upload_to='site_static/site/img', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
