# Generated by Django 2.2.11 on 2020-04-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0004_auto_20200405_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
