# Generated by Django 2.2.11 on 2020-04-05 02:47

from django.db import migrations, models
import hash.models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0005_auto_20200405_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(upload_to=hash.models.upload_to, verbose_name='Image'),
        ),
    ]
