# Generated by Django 2.2.11 on 2020-04-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0007_algorithm_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='description',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='paragraph1',
            field=models.TextField(default='', max_length=350, verbose_name='Description1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='paragraph2',
            field=models.TextField(default='', max_length=350, verbose_name='Description2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='paragraph3',
            field=models.TextField(default='', max_length=350, verbose_name='Description3'),
            preserve_default=False,
        ),
    ]
