# Generated by Django 2.2.11 on 2020-04-09 11:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bulletinboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinboard',
            name='image',
            field=models.ImageField(default='', upload_to=core.models.upload_to, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
